#--------------------------------------------------#
#      AppVeyor configuration for And Project      #
#--------------------------------------------------#

version: 0.1.{build}
branches:
  only:
    - master

# fetch repository as zip archive
shallow_clone: true

matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Release

# enable patching of AssemblyInfo.cs file
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "0.1.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform:
  - Any CPU

configuration: Debug

build:
  project: Source\And.sln

# notifications
# todo.